[influxdb] Fix checking of grafana repository usage
Before checking a value of grafana.enable we must ensure
that `grafana` is defined (means that fuel-ccp-grafana repo
is cloned and used).

jinja2.exceptions.UndefinedError: 'grafana' is undefined

Change-Id: I59fb2eb46df7f5a45c0902354931738b07d9eccb